# Generated by Django 5.2.16 on 2026-07-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("karnatic", "Karnatic"),
                            ("hindustani", "Hindustani"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("source_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "In review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.city",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.series",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="EventArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=80)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artists",
                        to="core.artist",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artists",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "artist", "role")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="artists",
            field=models.ManyToManyField(
                related_name="events", through="events.EventArtist", to="core.artist"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_at"], name="events_even_status_76ecd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["genre", "start_at"], name="events_even_genre_378829_idx"
            ),
        ),
    ]
