# Generated by Django 5.2.16 on 2026-07-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feed", "iCal/RSS feed"),
                            ("jsonld", "Embedded JSON-LD"),
                            ("api", "Open API"),
                            ("html", "Clean HTML"),
                            ("js", "JS-rendered HTML"),
                            ("email", "Inbound email"),
                            ("form", "Public form"),
                            ("social", "Social media"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("handle", models.CharField(blank=True, max_length=200)),
                ("scrape_method", models.CharField(blank=True, max_length=120)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("failing", "Failing"),
                            ("dead", "Dead"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("seasonal", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
